# 模型相关的配置文件
MODEL:
  # 模型文件
  WEIGHT: './weights/yolov8s-cls/weights/best.pt'
  # 取值 'cpu'、'0'、 '1'、 '2'、 '3'等 cpu代表以cpu进行推理，0代表使用第0块显卡进行推理
  DEVICE: 'cpu'
  # 阈值
  CONF: 0.4
  # 过滤类别
  CLASSES: None
  # 图片大小
  IMGSIZE: 300


UI:
  # 背景图片
  background: './icon/background.jpg'
  # 主图
  zhutu2: './icon/zhutu2.png'
  # 最上方的名称
  title: '野生菌菇检测识别系统'
  # 名称
  label_title: '野生菌菇检测识别系统'
  # 开始识别按钮背景颜色
  start_button_bg: "71,43,22"
  # 开始识别按钮字体颜色
  start_button_font: "255,255,255"
  # 导出数据按钮颜色
  export_button_bg: "71,43,22"
  # 导出数据按钮字体颜色
  export_button_font: "255,255,255"
  # 图片填充 RGB格式
  padvalue: [ 187,191,164 ]
  # 表格每列的宽度
  column_widths: [ 50, 220, 120, 200, 80, 80, 140 ]
  # 表格中字体的颜色 RGB格式
  column_color: [ 0, 0, 0 ]
  # 个人信息
  label_info_txt: "姓名: 刘福应                      学号: 20211120228                             专业: 计算机科学与技术"
  # 个人信息字体颜色 RGB 格式
  label_info_color: " 0 , 0 , 0 "
  # 左侧控制区域颜色 RGBA
  label_control_color: "161,160,141, 100"
  # 主图区域颜色
  label_img_color: "161,160,141, 100"
  # class背景颜色
  label_class_color: "135,118,108"
  # 表格相关
  table_widget_info_styles:
    # 表头背景
    header_background_color: "71,43,22"
    # 表头字体
    header_color: "112,63,46"
    # 表格背景
    background_color: "197,190,172"
    # 滑过背景
    item_hover_background_color: "71,43,22"


CONFIG:
  # 摄像头id,如果发现打开摄像头没有画面，修改下面的数值 0 1 2 3 等
  camera_num: 0
  chinese_name:
    {
      "Agaricus": "蘑菇",
      "Amanita": "鹅膏",
      "Boletus": "牛肝菌",
      "Cortinarius": "丝膜菌",
      "Entoloma": "粉褶菌",
      "Hygrocybe": "蜡伞",
      "Lactarius": "乳菇",
      "Russula": "红菇",
      "Suillus": "粘盖牛肝菌",
      '无目标': '无目标' }

